In [1]:
import numpy as np
import pandas as pd

## What are the three longest trips on rainy days?

WITH
    raindays
AS (
    SELECT
        Date,
        ZIP
    FROM
        weather
    WHERE
        Events like 'Rain'
)

SELECT
    trips.trip_id trip_id,
    trips.start_station,
    trips.end_station,
    date(trips.start_date) date,
    trips.zip_code zip_code,
    trips.duration duration
   
FROM
    trips
JOIN
    raindays
ON
    (date(trips.start_date) = raindays.Date AND trips.zip_code = raindays.ZIP)
ORDER BY
	duration DESC
limit 3

In [5]:
raintrips = pd.read_csv('raintrips.csv')

raintrips

   trip_id        date  zip_code  duration
0  1068614  2016-01-22     94107     62168
1  1076000  2016-01-29     94107     28263
2  1162895  2016-04-14     94041     24831

## Which station is full most often?

with
	stations_full
AS (
	SELECT
		station_id,
		COUNT(timestamp) fullcount
	FROM
		status
	WHERE
		docks_available = 0
	GROUP BY
		station_id
	ORDER BY
		COUNT(timestamp) DESC
)

SELECT
	stations.name,
	stations.dockcount,
	stations.station_id,
	stations_full.fullcount
FROM
	stations
JOIN
	stations_full
ON
	stations.station_id = stations_full.station_id
ORDER BY
	stations_full.fullcount desc

In [9]:
frequent_full = pd.read_csv('frequent_full.csv')

frequent_full

,name,dockcount,station_id,fullcount
0,San Francisco Caltrain (Townsend at 4th),19,70,23450
1,Grant Avenue at Columbus Avenue,19,73,12338
2,San Francisco Caltrain 2 (330 Townsend),23,69,9852
3,Embarcadero at Bryant,15,54,9231
4,Harry Bridges Plaza (Ferry Building),23,50,7590
5,2nd at Townsend,27,61,6372
6,Embarcadero at Sansome,15,60,5894
7,Embarcadero at Vallejo,15,48,5868
8,Santa Clara at Almaden,11,4,5788
9,Townsend at 7th,15,65,5279
10,Howard at 2nd,19,63,4998
11,Ryland Park,15,84,4949
12,2nd at South Park,15,64,4740
13,Steuart at Market,23,74,3992
14,Commercial at Montgomery,15,45,2916
15,Cowper at University,11,37,2402
16,Mountain View City Hall,15,27,2359
17,5th at Howard,15,57,2282
18,Powell Street BART,19,39,1874
19,California Ave Caltrain Station,15,36,1745
20,Davis at Jackson,15,42,1608
21,Temporary Transbay Terminal (Howard at Beale),23,55,1528
22,San Jose Civic Center,15,3,1444
23,Washington at Kearney,15,46,1342
24,Market at 4th,19,76,1251
25,University and Emerson,11,35,1193
26,Clay at Battery,15,41,1100
27,Powell at Post (Union Square),19,71,1075
28,Beale at Market,19,56,1064
29,San Pedro Square,15,6,1037
30,Broadway St at Battery St,15,82,953
31,Mechanics Plaza (Market at Battery),19,75,939
32,Mountain View Caltrain Station,23,28,868
33,Charleston Park/ North Bayshore Area,15,33,852
34,Paseo de San Antonio,15,7,829
35,SJSU - San Salvador at 9th,15,16,681
36,Embarcadero at Folsom,19,51,670
37,San Jose Diridon Caltrain Station,27,2,626
38,Japantown,15,9,604
39,Market at Sansome,27,77,578
40,2nd at Folsom,19,62,567
41,SJSU 4th at San Carlos,19,12,550
42,MLK Library,19,11,487
43,Spear at Folsom,19,49,408
44,Yerba Buena Center of the Arts (3rd @ Howard),19,68,375
45,St James Park,15,13,321
46,Castro Street and El Camino Real,11,32,289
47,Post at Kearney,19,47,287
48,San Salvador at 1st,15,8,270
49,Adobe on Almaden,19,5,179
50,San Francisco City Hall,19,58,152
51,South Van Ness at Market,19,66,130
52,Market at 10th,27,67,41
53,Civic Center BART (7th at Market),23,72,6
54,5th St at Folsom St,31,90,5
55,5th S. at E. San Salvador St,19,88,3
56,S. Market st at Park Ave,19,89,2
57,San Antonio Shopping Center,15,31,2
58,Cyril Magnin St at Ellis St,35,91,1

## Return a list of stations with a count of number of trips starting at that station but ordered by dock count.

SELECT
	stations.name name,
	count(trips.start_station) trip_count,
	stations.dockcount docks
FROM
	trips
JOIN
	stations
ON
	trips.start_station = stations.name
GROUP BY
	stations.name
ORDER BY
	stations.dockcount

In [7]:
numtrips_orderdocks = pd.read_csv('numtrips.csv')

numtrips_orderdocks

                                             name  trip_count  docks
0                Castro Street and El Camino Real        1014     11
1                            Cowper at University         788     11
2                          Santa Clara at Almaden        1447     11
3                          University and Emerson         490     11
4                               2nd at South Park        7722     15
5                                   5th at Howard        5436     15
6                       Broadway St at Battery St        5695     15
7                 California Ave Caltrain Station         392     15
8            Charleston Park/ North Bayshore Area         343     15
9                                 Clay at Battery        4357     15
10                       Commercial at Montgomery        4969     15
11                               Davis at Jackson        5240     15
12                          Embarcadero at Bryant        7714     15
13                         Embarcadero at Sansome       13424     15
14                         Embarcadero at Vallejo        4710     15
15                                      Japantown         945     15
16                 Middlefield Light Rail Station          66     15
17                        Mountain View City Hall        1291     15
18                                  Park at Olive         276     15
19                           Paseo de San Antonio         833     15
20                                    Ryland Park         879     15
21                     SJSU - San Salvador at 9th         481     15
22                    San Antonio Shopping Center         559     15
23                             San Jose City Hall         518     15
24                          San Jose Civic Center         543     15
25                               San Pedro Square        1215     15
26                            San Salvador at 1st         540     15
27                Santa Clara County Civic Center         420     15
28                                  St James Park         694     15
29                                Townsend at 7th       11170     15
..                                            ...         ...    ...
33                                Beale at Market        7373     19
34                          Embarcadero at Folsom        7820     19
35                Grant Avenue at Columbus Avenue        6735     19
36                                  Howard at 2nd        7583     19
37                                    MLK Library         630     19
38                                  Market at 4th        7337     19
39            Mechanics Plaza (Market at Battery)        5613     19
40                             Powell Street BART        6826     19
41                  Powell at Post (Union Square)        4488     19
42                         SJSU 4th at San Carlos         363     19
43       San Francisco Caltrain (Townsend at 4th)       23591     19
44                        San Francisco City Hall        2195     19
45                       South Van Ness at Market        5398     19
46                                Spear at Folsom        5113     19
47  Yerba Buena Center of the Arts (3rd @ Howard)        3460     19
48              Civic Center BART (7th at Market)        5043     23
49                            Golden Gate at Polk        3309     23
50           Harry Bridges Plaza (Ferry Building)       16128     23
51                 Mountain View Caltrain Station        2515     23
52                     Palo Alto Caltrain Station        1170     23
53                   San Antonio Caltrain Station         611     23
54        San Francisco Caltrain 2 (330 Townsend)       22358     23
55                              Steuart at Market       13693     23
56  Temporary Transbay Terminal (Howard at Beale)       13111     23
57                                2nd at Townsend       14099     27
58                                 Market at 10th        9937     27
59                              Market at Sansome       10970     27
60              San Jose Diridon Caltrain Station        4035     27
61                            5th St at Folsom St         173     31
62                    Cyril Magnin St at Ellis St          69     35

[63 rows x 3 columns]

## (Challenge) What's the length of the longest trip for each day it rains anywhere?

WITH
    raindays
AS (
    SELECT
        Date
    FROM
        weather
    WHERE
        Events like 'Rain'
),
    raintrips
AS (
    SELECT
        trips.trip_id trip_id,
        date(trips.start_date) date,
        trips.duration duration
   
    FROM
        trips
    JOIN
        raindays
    ON
        date(trips.start_date) = raindays.Date
    ORDER BY
        duration DESC
)

SELECT
    date,
    max(duration)
FROM
    raintrips
GROUP BY
	date

In [10]:
longest_raintrip = pd.read_csv('longest_raintrip.csv')

longest_raintrip

          date  max(duration)
0   2015-09-02          25917
1   2015-09-13          21695
2   2015-09-16          50241
3   2015-09-30          25667
4   2015-10-01          51081
5   2015-10-15          27467
6   2015-10-16          19073
7   2015-10-19          41555
8   2015-10-27          11107
9   2015-11-01          43899
10  2015-11-02          12246
11  2015-11-08           7874
12  2015-11-09          12838
13  2015-11-10          61234
14  2015-11-12          37799
15  2015-11-15          84349
16  2015-11-24          22478
17  2015-11-25           3617
18  2015-11-30          58759
19  2015-12-03          16722
20  2015-12-06          39450
21  2015-12-10           8540
22  2015-12-11          19186
23  2015-12-13          57019
24  2015-12-18          27880
25  2015-12-19          33629
26  2015-12-20          13739
27  2015-12-21          18927
28  2015-12-22           3999
29  2015-12-24           8472
..         ...            ...
62  2016-03-04          26338
63  2016-03-05           1878
64  2016-03-06          24693
65  2016-03-07          41493
66  2016-03-08          21212
67  2016-03-09           7375
68  2016-03-10          12285
69  2016-03-11          24845
70  2016-03-12          46320
71  2016-03-13           3769
72  2016-03-14          41092
73  2016-03-20          36895
74  2016-03-21          27357
75  2016-03-22          67375
76  2016-03-28          30027
77  2016-04-08          78123
78  2016-04-09           6220
79  2016-04-10          43422
80  2016-04-14          50495
81  2016-04-21          14883
82  2016-04-22          85900
83  2016-04-27           6565
84  2016-05-06          59642
85  2016-05-07          82896
86  2016-05-08          18632
87  2016-05-09          28055
88  2016-05-21          83915
89  2016-06-14          25396
90  2016-06-17          81687
91  2016-07-18          52051

[92 rows x 2 columns]